stages:
  - test
  - build
  - deploy
  
flutter-test-macos:
  stage: test
  script:
    - ./ci/01-macos-test.sh
  tags:
    - os=macos
    - flutter_build_ios=true
  
flutter-test-linux:
  stage: test
  image: cirrusci/flutter:beta
  script:
    - ./ci/01-linux-test.sh