stages:
  - test
  - build
  - deploy
  
flutter-test:
  stage: test
  script:
    - whoami
    - uname -a
    - ls -al
    - pwd
    - env
    - flutter test
  tags:
    - os=macos
    - flutter_build_ios=true
  
