stages:
  - test
  - build
  - deploy
  
flutter-test-macos:
  stage: test
  variables:
    GITHUB_STATUS_CONTEXT: "ci/test/ios"
  script:
    - ./ci/01-macos-test.sh
  tags:
    - os=macos
    - flutter_build_ios=true
  
flutter-test-linux:
  stage: test
  variables:
    GITHUB_STATUS_CONTEXT: "ci/test/android"
  image: xertrov/flutter:beta
  script:
    - ./ci/01-linux-test.sh
  tags:
    - os=linux
    - flutter_build_android=true
